version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'demo1'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'evavilla'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  app:
    image: "evav183/peliculas:0.0.1"
    environment:
      DATASOURCES_DEFAULT_URL: "jdbc:mysql://db:3306/demo1"
    ports:
      - '8080:8080'
    expose:
      - '8080'

# Names our volume
volumes:
  my-db: